apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "slack-service.fullname" . }}
  labels:
    {{- include "slack-service.labels" . | nindent 4 }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/contact: {{ .Values.labels.contact }}
    app.kubernetes.io/workload: {{ .Values.labels.workload }}
    app.kubernetes.io/env: {{ .Values.labels.env }}
    app.kubernetes.io/tier: {{ .Values.labels.tier }}
    app.kubernetes.io/project: {{ .Values.labels.project }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "slack-service.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/version: {{ .Chart.Version }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      app.kubernetes.io/contact: {{ .Values.labels.contact }}
      app.kubernetes.io/workload: {{ .Values.labels.workload }}
      app.kubernetes.io/env: {{ .Values.labels.env }}
      app.kubernetes.io/tier: {{ .Values.labels.tier }}
      app.kubernetes.io/project: {{ .Values.labels.project }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "slack-service.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.Version }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/contact: {{ .Values.labels.contact }}
        app.kubernetes.io/workload: {{ .Values.labels.workload }}
        app.kubernetes.io/env: {{ .Values.labels.env }}
        app.kubernetes.io/tier: {{ .Values.labels.tier }}
        app.kubernetes.io/project: {{ .Values.labels.project }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "slack-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PORT
              value: {{ .Values.env.PORT | quote }}
          ports:
            - name: http
              containerPort: 3007
              protocol: TCP
            - name: grpcport
              containerPort: 53007
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /files
              name: public-files
            - mountPath: /private-files
              name: private-files
      volumes:
      - name: public-files
        persistentVolumeClaim:
          claimName: {{ include "slack-service.fullname" . }}-public-files
      - name: private-files
        persistentVolumeClaim:
          claimName: {{ include "slack-service.fullname" . }}-private-files
      - azureFile:
          secretName: dwk8sdatastorage-secret
          shareName: data
        name: data
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
