apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jobfactory.fullname" . }}-secret
  labels:
    {{- include "jobfactory.labels" . | nindent 4 }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/contact: {{ .Values.labels.contact }}
    app.kubernetes.io/workload: {{ .Values.labels.workload }}
    app.kubernetes.io/env: {{ .Values.labels.env }}
    app.kubernetes.io/tier: {{ .Values.labels.tier }}
    app.kubernetes.io/project: {{ .Values.labels.project }}
type: opaque
data:
  AZURE_STORAGE_ACCESS_KEY: {{ .Values.env.AZURE_STORAGE_ACCESS_KEY| b64enc | quote }}
  AZURE_STORAGE_ACCOUNT: {{ .Values.env.AZURE_STORAGE_ACCOUNT| b64enc | quote }}
