apiVersion: v1
kind: Secret
metadata:
  name: {{ include "config-data-management.fullname" . }}-secret
  labels:
    {{- include "config-data-management.labels" . | nindent 4 }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/contact: {{ .Values.labels.contact }}
    app.kubernetes.io/workload: {{ .Values.labels.workload }}
    app.kubernetes.io/env: {{ .Values.labels.env }}
    app.kubernetes.io/tier: {{ .Values.labels.tier }}
    app.kubernetes.io/project: {{ .Values.labels.project }}
type: opaque
data:
  AZURE_STORAGE_ACCESS_KEY: {{ .Values.env.AZURE_STORAGE_ACCESS_KEY | b64enc | quote }}
  AZURE_STORAGE_ACCOUNT: {{ .Values.env.AZURE_STORAGE_ACCOUNT | b64enc | quote }}
  JWT: {{ .Values.env.JWT | b64enc | quote }}
  MONGO_DB: {{ .Values.env.MONGO_DB | b64enc | quote }}
  MONGO_DB_TEST: {{ .Values.env.MONGO_DB_TEST | b64enc | quote }}
  MONGO_HOST: {{ .Values.env.MONGO_HOST | b64enc | quote }}
  MONGO_PORT: {{ .Values.env.MONGO_PORT | b64enc | quote }}
  POSTGRES_DB: {{ .Values.env.POSTGRES_DB | b64enc | quote }}
  POSTGRES_DB_TEST: {{ .Values.env.POSTGRES_DB_TEST | b64enc | quote }}
  POSTGRES_HOST: {{ .Values.env.POSTGRES_HOST | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.env.POSTGRES_PASSWORD | b64enc | quote }}
  POSTGRES_PORT: {{ .Values.env.POSTGRES_PORT | b64enc | quote }}
  POSTGRES_USER: {{ .Values.env.POSTGRES_USER | b64enc | quote }}
  REDIS_HOST: {{ .Values.env.REDIS_HOST | b64enc | quote }}
  REDIS_PORT: {{ .Values.env.REDIS_PORT | b64enc | quote }}
  SESSION_KEY: {{ .Values.env.SESSION_KEY | b64enc | quote }}

