apiVersion: v1
name: centrifugo
description: Centrifugo is a scalable real-time messaging server in language-agnostic way
version: 7.1.5
appVersion: 3.0.5
home: https://centrifugal.dev
icon: https://centrifugal.dev/img/favicon.png
maintainers:
  - name: FZambia
    email: frvzmb@gmail.com
engine: gotpl
