apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "scheduler.fullname" . }}
  labels:
    {{- include "scheduler.labels" . | nindent 4 }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/contact: {{ .Values.labels.contact }}
    app.kubernetes.io/workload: {{ .Values.labels.workload }}
    app.kubernetes.io/env: {{ .Values.labels.env }}
    app.kubernetes.io/tier: {{ .Values.labels.tier }}
    app.kubernetes.io/project: {{ .Values.labels.project }}
spec:
  serviceName: scheduler
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "scheduler.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/version: {{ .Chart.Version }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      app.kubernetes.io/contact: {{ .Values.labels.contact }}
      app.kubernetes.io/workload: {{ .Values.labels.workload }}
      app.kubernetes.io/env: {{ .Values.labels.env }}
      app.kubernetes.io/tier: {{ .Values.labels.tier }}
      app.kubernetes.io/project: {{ .Values.labels.project }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "scheduler.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.Version }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/contact: {{ .Values.labels.contact }}
        app.kubernetes.io/workload: {{ .Values.labels.workload }}
        app.kubernetes.io/env: {{ .Values.labels.env }}
        app.kubernetes.io/tier: {{ .Values.labels.tier }}
        app.kubernetes.io/project: {{ .Values.labels.project }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "scheduler.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PORT
              value: {{ .Values.env.PORT | quote }}
            - name: GRPC_CRUD_SERVICE
              value: {{ .Values.env.GRPC_CRUD_SERVICE | quote }}
            - name: GRPC_CRUD_PORT
              value: {{ .Values.env.GRPC_CRUD_PORT | quote}}
            - name: GRPC_JOBFACTORY_SERVICE
              value: {{ .Values.env.GRPC_JOBFACTORY_SERVICE | quote }}
            - name: GRPC_JOBFACTORY_PORT
              value: {{ .Values.env.GRPC_JOBFACTORY_PORT | quote }}
            - name: REDIS_HOST
              value: {{ .Values.env.REDIS_HOST | quote }}
            - name: REDIS_PORT
              value: {{ .Values.env.REDIS_PORT | quote }}
            - name: INDEXING_SERVICE
              value: {{ .Values.env.INDEXING_SERVICE | quote }}
            - name: INDEXING_PORT
              value: {{ .Values.env.INDEXING_PORT | quote }}
            - name: OUTPUT_STORAGE
              value: {{ .Values.env.OUTPUT_STORAGE | quote }}
          ports:
            - name: http
              containerPort: 3005
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - azureFile:
            secretName: dwk8sdatastorage-secret
            shareName: data
          name: data
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
