{{- if eq .Values.turn "off" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Release.Name}}-scale-down-post-install-hook"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
#  ttlSecondsAfterFinished: 60
  template:
    spec:
      serviceAccount: scale-stack
      securityContext:
        runAsUser: 0
        # runAsGroup: 3000
        # fsGroup: 2000
      containers:
      - name: post-install-scale-down-job
        image: nginx
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash", "-c", "/tmp/script/turn-off.sh"]
        volumeMounts:
          - name: config-volume
            mountPath: /tmp/script
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-turn-off
            defaultMode: 0777
      restartPolicy: Never
      terminationGracePeriodSeconds: 0
{{- end }}
