apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "indexingservice.fullname" . }}
  labels:
    {{- include "indexingservice.labels" . | nindent 4 }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/contact: {{ .Values.labels.contact }}
    app.kubernetes.io/workload: {{ .Values.labels.workload }}
    app.kubernetes.io/env: {{ .Values.labels.env }}
    app.kubernetes.io/tier: {{ .Values.labels.tier }}
    app.kubernetes.io/project: {{ .Values.labels.project }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "indexingservice.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/version: {{ .Chart.Version }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      app.kubernetes.io/contact: {{ .Values.labels.contact }}
      app.kubernetes.io/workload: {{ .Values.labels.workload }}
      app.kubernetes.io/env: {{ .Values.labels.env }}
      app.kubernetes.io/tier: {{ .Values.labels.tier }}
      app.kubernetes.io/project: {{ .Values.labels.project }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "indexingservice.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.Version }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/contact: {{ .Values.labels.contact }}
        app.kubernetes.io/workload: {{ .Values.labels.workload }}
        app.kubernetes.io/env: {{ .Values.labels.env }}
        app.kubernetes.io/tier: {{ .Values.labels.tier }}
        app.kubernetes.io/project: {{ .Values.labels.project }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "indexingservice.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PORT
              value: {{ .Values.env.PORT | quote }}
            - name: MONGO_HOST
              value: {{ .Values.env.MONGO_HOST | quote }}
            - name: MONGO_PORT
              value: {{ .Values.env.MONGO_PORT | quote }}
            - name: MONGO_DB
              value: {{ .Values.env.MONGO_DB | quote }}
            - name: TAXONOMIES_STORAGE
              value: {{ .Values.env.TAXONOMIES_STORAGE | quote }}
            - name: SLACK_HOST
              value: {{ .Values.env.SLACK_HOST | quote }}
            - name: SLACK_PORT
              value: {{ .Values.env.SLACK_PORT | quote }}
            - name: CRUD_HOST
              value: {{ .Values.env.CRUD_HOST | quote }}
            - name: CRUD_PORT
              value: {{ .Values.env.CRUD_PORT | quote }}
            - name: GRPC_PORT
              value: {{ .Values.env.GRPC_PORT | quote }}
            - name: POSTGRES_HOST
              value: {{ .Values.env.POSTGRES_HOST | quote }}
            - name: POSTGRES_PORT
              value: {{ .Values.env.POSTGRES_PORT | quote }}
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  key: postgres_db
                  name: {{ include "indexingservice.fullname" . }}-secret
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: postgres_password
                  name: {{ include "indexingservice.fullname" . }}-secret
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgres_user
                  name: {{ include "indexingservice.fullname" . }}-secret
          ports:
            - name: http
              containerPort: 1323
              protocol: TCP
            - name: grpcport
              containerPort: 51323
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /files
              name: public-files
            - mountPath: /private-files
              name: private-files
      volumes:
      - name: public-files
        persistentVolumeClaim:
          claimName: {{ include "indexingservice.fullname" . }}-public-files
      - name: private-files
        persistentVolumeClaim:
          claimName: {{ include "indexingservice.fullname" . }}-private-files
      - azureFile:
          secretName: dwk8sdatastorage-secret
          shareName: data
        name: data
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
