apiVersion: v1
items:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    creationTimestamp: "2021-04-18T17:43:24Z"
    name: jaeger-operator-lock
    namespace: dataworks
    ownerReferences:
    - apiVersion: v1
      kind: Pod
      name: jaeger-operator-fdd88dd95-wr79d
      uid: 0068a13d-08a5-4950-a151-4a90ae276ef0
    resourceVersion: "63595201"
    selfLink: /api/v1/namespaces/dataworks/configmaps/jaeger-operator-lock
    uid: 396ceac1-7a4e-478c-8a79-80f4621bcb77
- apiVersion: v1
  data:
    prometheus.yml: |
      global:
          scrape_interval: 15s
      scrape_configs:
        - job_name: 'prometheus'
          static_configs:
            - targets: ['localhost:9090']
        - job_name: 'kubernetes-pods'
          kubernetes_sd_configs:
            - role: pod
        - job_name: kafkaesque-service
          scrape_interval: 30s
          scrape_timeout: 10s
          metrics_path: /pulsarmetrics
          scheme: https
          static_configs:
          - targets:
            - uscentral1.azure.kafkaesque.io:8964
          bearer_token: eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXJpdC10aGVkYXRhd29ya3MtY29tLWNsaWVudC01ZWIyZGZkYjYyMjQxIn0.AExoesCB4IFmLIZM-B4zo3xpR-6ZjXBLzLz7psfC0sT5TAn1qGkZ_dAhf3GbMoujum9DsL3cfOfYd53gH-mwxcY6a4EFV_h-4EDlBWXYo-Q44d4S3U9qqlRIpt1aybckIvmMdB5N9x45_hBVHvzBARTB8GY-6dbvAlecpBVf67T_iaVewvw-Pkq4Prz12FkT7cyfEvWFVSmJUAmsWZH40Wb6bv3KL0P8kqdN90x6HT2fukMl6EC6JB2ZRBVpG-qzrmk5weblk1APKcnRyrHAZlxVk9d6511cQQpkpkTXzGOvVbATQTEjpxqFGUkPlpcQT67dfUyFJthqhHC_zD4XqQ

          relabel_configs:
            - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
              action: keep
              regex: true
            - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
              action: replace
              target_label: __metrics_path__
              regex: (.+)
            - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
              action: replace
              regex: ([^:]+)(?::\d+)?;(\d+)
              replacement: $1:$2
              target_label: __address__
            - action: labelmap
              regex: __meta_kubernetes_pod_label_(.+)
            - source_labels: [__meta_kubernetes_namespace]
              action: replace
              target_label: kubernetes_namespace
            - source_labels: [__meta_kubernetes_pod_label_component]
              action: replace
              target_label: job
            - source_labels: [__meta_kubernetes_pod_name]
              action: replace
              target_label: kubernetes_pod_name
  kind: ConfigMap
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","data":{"prometheus.yml":"global:\n    scrape_interval: 15s\nscrape_configs:\n  - job_name: 'prometheus'\n    static_configs:\n      - targets: ['localhost:9090']\n  - job_name: 'kubernetes-pods'\n    kubernetes_sd_configs:\n      - role: pod\n  - job_name: kafkaesque-service\n    scrape_interval: 30s\n    scrape_timeout: 10s\n    metrics_path: /pulsarmetrics\n    scheme: https\n    static_configs:\n    - targets:\n      - uscentral1.azure.kafkaesque.io:8964\n    bearer_token: eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXJpdC10aGVkYXRhd29ya3MtY29tLWNsaWVudC01ZWIyZGZkYjYyMjQxIn0.AExoesCB4IFmLIZM-B4zo3xpR-6ZjXBLzLz7psfC0sT5TAn1qGkZ_dAhf3GbMoujum9DsL3cfOfYd53gH-mwxcY6a4EFV_h-4EDlBWXYo-Q44d4S3U9qqlRIpt1aybckIvmMdB5N9x45_hBVHvzBARTB8GY-6dbvAlecpBVf67T_iaVewvw-Pkq4Prz12FkT7cyfEvWFVSmJUAmsWZH40Wb6bv3KL0P8kqdN90x6HT2fukMl6EC6JB2ZRBVpG-qzrmk5weblk1APKcnRyrHAZlxVk9d6511cQQpkpkTXzGOvVbATQTEjpxqFGUkPlpcQT67dfUyFJthqhHC_zD4XqQ\n\n    relabel_configs:\n      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]\n        action: keep\n        regex: true\n      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]\n        action: replace\n        target_label: __metrics_path__\n        regex: (.+)\n      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]\n        action: replace\n        regex: ([^:]+)(?::\\d+)?;(\\d+)\n        replacement: $1:$2\n        target_label: __address__\n      - action: labelmap\n        regex: __meta_kubernetes_pod_label_(.+)\n      - source_labels: [__meta_kubernetes_namespace]\n        action: replace\n        target_label: kubernetes_namespace\n      - source_labels: [__meta_kubernetes_pod_label_component]\n        action: replace\n        target_label: job\n      - source_labels: [__meta_kubernetes_pod_name]\n        action: replace\n        target_label: kubernetes_pod_name\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"prometheus-config1","namespace":"dataworks"}}
    creationTimestamp: "2020-08-19T06:28:31Z"
    name: prometheus-config1
    namespace: dataworks
    resourceVersion: "103956"
    selfLink: /api/v1/namespaces/dataworks/configmaps/prometheus-config1
    uid: 9a76befe-d32c-477b-a9f7-3e98fddd6a10
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
