apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "hpa-scaling.fullname" . }}-pulsar-proxy
  namespace: dataworks-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: pulsar-proxy
  minReplicas: {{ .Values.pulsar.proxy.minReplicas }}
  maxReplicas: {{ .Values.pulsar.proxy.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 350
