apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-fission-function
data:
  fission-functions.sh: |-
    #!/bin/bash
    curl -Lo fission https://github.com/fission/fission/releases/download/1.11.0/fission-cli-linux
    chmod 777 fission
    mv fission /usr/local/bin/
    git clone https://$GIT_USER:$GIT_PASSWORD@github.com/webdataworks/fission-function.git -b dev
    cd /fission-function
    fission function update --name go-hello --env go --src hello.go --entrypoint Handler
    fission httptrigger update --url /hello --method GET --function go-hello --name hello-go-trigger
    fission function update --name sacler-go --env go --src scaler.go --entrypoint Handler
    fission httptrigger update --url /scale --method GET --function sacler-go --name scaler-trigger
